#3.14-rc-alpine

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER=
      POSTGRES_PASSWORD=


--name postgres_preregistro
-e POSTGRES_USER=admin
-e POSTGRES_PASSWORD=admin123
-e POSTGRES_DB=preregistro
-p 5435:5432
-v pgdata:/var/lib/postgresql/data_preregistro
-d postgres:latest